### ISSUE TITLE
Can i use this SDK in Malaysia ?

### ISSUE THREAD

**Issue by itw2016** [TapPay/tappay-ios-t2p-sdk#6]
Hi, i would like to use this SDK for tap to pay on iPhone in Malaysia...
Is it working for Malaysia ?
If no, may I know the reason and the alternative ? Pls advise detail

Thank you
Matthew

**Comment by Isme-Cherri** [comment]
This SDK is built on the foundation of Apple’s Tap to Pay on iPhone SDK. When integrating this SDK, it is necessary to obtain Apple’s consent to use the developer's Tap to Pay on iPhone feature. Currently, Tap to Pay on iPhone has not been introduced in Malaysia. Additionally, this SDK was constructed by TapPay as a payment service provider for device binding and transaction sending. However, TapPay does not currently offer this service in Malaysia, so it is not available for use at the moment.

**Comment by itw2016** [comment]
Thank you for clear explanation
